### PR TITLE
Update dependencies to released versions

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
There are several branch-based dependencies that need to be updated to the recently released 1.0 versions. (per @mattcollier's request)

WIP, do not merge yet.

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Skipping the `"bedrock": "digitalbazaar/bedrock#cliParsed",` dependency for the moment.

**Comment by dmitrizagidulin** [comment]
Reminder to self to ask @dlongley about `"bedrock-did-client": "digitalbazaar/bedrock-did-client#jsonld-1.1",`. 

The `jsonld-1.1` branch uses the old authorize.io code. Does that mean that lib is unused?

**Comment by dlongley** [comment]
@dmitrizagidulin, that library is either unused (and should be removed) or it should be updated. Someone will need to audit to figure out if we need it. That lib was responsible for hooking up requests for DID docs so that they use cached contexts and hit Veres One (... or something along those lines). There is a new version of it that is supposed to use the new did-io (I think). That doesn't mean Veres One necessarily needs it, however.

**Comment by mattcollier** [comment]
@dmitrizagidulin bedrock-did-client v2 has been released which utilizes did-io 0.7.x.

**Comment by mattcollier** [comment]
@dmitrizagidulin with commit 098020a92641c639b89d2e6287a822fcc3628fc3 veres-one will install and run the test.  (there is only one right now).

We now know that there is no need for any rev of veres-one at all that does not include the *very* latest releases of all the things.  So, I'll be making another pass on the package files here to rev up all the things to bedrock-validation 3.x compatible versions later today.

Then, we get one test that involves using did-io#development to create a DID.

**Comment by mattcollier** [comment]
As of 5189bf7c6ce0ff84d318bf8cedb4727bdc372cb6 

1. all ledger deps are updated to latest
2. installs and test runs
3. Using did-io#development (should we be using did-veres-one in the tests instead of did-io directly?)
4. DID is being generated and transmitted 
5. DID is being rejected to to json-schema validation error (TBD)
6. However, did-io seems to be failing silently, possibly due to error handling in r2 as discussed earlier today.

I'll be investigating the cause of the schema validation failure.

**Comment by dmitrizagidulin** [comment]
> should we be using did-veres-one in the tests instead of did-io directly? 

Lets use did-io directly. (It uses code extracted from did-veres-one).

I'm in the process of switching r2 to axios, in the web-ledger-client, so maybe that'll shed some light on the errors.

**Comment by mattcollier** [comment]
@dmitrizagidulin is did-veres-one going to be a thing?  Or is all the functionality going into did-io?

**Comment by dmitrizagidulin** [comment]
@mattcollier possibly? I heard requests to pull out any Veres-specific code out of did-io, so maybe that'll go into `did-veres-one`? For the moment, did-io is all-on-one :)

**Comment by dmitrizagidulin** [comment]
@mattcollier Ooh, that doesn't seem right... Investigating.

**Comment by dmitrizagidulin** [comment]
@mattcollier Ok, so, just generating a DID Document just links to the `@context`, as expected (I just double-checked). 

Ohhh, I bet I know what it is. the `wrap()` operation...

Yeah, it seems to be embedding the context... Stand by, fixing :)

**Comment by dmitrizagidulin** [comment]
@mattcollier ok, should be fixed now in latest `web-ledger-client` / `development`. (Will need deleting & re npm-installing did-io & web-ledger-client deps :) ).

**Comment by mattcollier** [comment]
@dmitrizagidulin looks better: https://gist.github.com/mattcollier/bc64eefc0e959816344042f854a75565

However, we have a requirement that the context on a `CreateWebLedgerRecord` document must have the WebLedger context as the only context or the first in the @context array.  I think you can just replace the veres-one context there with webledger right?  Leaving the veres-one context in the `record`.

https://github.com/digitalbazaar/bedrock-ledger-node/blob/master/lib/LedgerNodeOperations.js#L74

**Comment by dmitrizagidulin** [comment]
@mattcollier k, try now, should be fixed in `development`.

**Comment by mattcollier** [comment]
@dmitrizagidulin getting close I think.  At this point, I have a failure in the veres-one-validator see this gist for details: https://gist.github.com/mattcollier/b3f3f031e4e750df2ce7bc6fef6a3408

**Comment by dmitrizagidulin** [comment]
@mattcollier does the validation error give any hints on what it might be?

**Comment by mattcollier** [comment]
@dmitrizagidulin this is not a schema validation issue at this point.  In the gist, I referenced the validator code that is generating the expected DID based on the provided public key in the DID Document for a check.  The validator and did-io are currently producing different values.  Have you updated did-io to generate cryptonyms (which is what the validator is expecting)?

**Comment by mattcollier** [comment]
@dmitrizagidulin if you do a fresh install on commit 5189bf7c6ce0ff84d318bf8cedb4727bdc372cb6

and run the test framework here, you should see something like this: https://gist.github.com/mattcollier/5861590b2360e555126a35dca971e60b#file-test-txt-L58-L61

I've left logging in the #promises branch of veres-one-validator here: https://github.com/veres-one/veres-one-validator/blob/49825abb5903f9c94d94be301890dba9bc4ede3a/lib/index.js#L194-L197

I believe we're OK as far as schema validation goes, just need to reconcile the differences between the DIDs that did-io is creating and what the validator is expecting.

**Comment by dmitrizagidulin** [comment]
@mattcollier ahh ok, investigating

**Comment by dmitrizagidulin** [comment]
@mattcollier I'm having trouble getting the tests to run, getting a

```
TypeError: Cannot read property 'permissions' of undefined
    at Object.<anonymous> (/Users/dmitri/code/_DigitalBazaar/veres-one/test/test.config.js:8:39)
```

Looking into it.

**Comment by mattcollier** [comment]
@dmitrizagidulin the test suite on this module is unusual in that you have to run npm install in the root of the module AND the test folder, then run npm test from the test folder.

**Comment by dmitrizagidulin** [comment]
@mattcollier ahaa, thanks!

**Comment by mattcollier** [comment]
@dmitrizagidulin want to make sure you're aware that did-io just needs to implement this exact same algorithm (including the use of the did-veres-one dependency) to compute a cryptonym DID:

https://github.com/veres-one/veres-one-validator/blob/promises/lib/index.js#L164-L193

**Comment by mattcollier** [comment]
@dmitrizagidulin I see that after updating to did-io#multihash here that the DID creation test here is now passing.  That's great!  :)

Now, I'm curious about the return value of `register` here: https://github.com/veres-one/veres-one/blob/62672bd18c7a053d78e97a65a85851af08892d8b/test/mocha/20-create.js#L42-L43

Which is 
```
{
  "size": 0,
  "timeout": 0
}
```

Is this proper, and what is it telling us?

**Comment by dmitrizagidulin** [comment]
@mattcollier oh excellent! 

re size: / register: -- sooo, I think that part is just mocked up. I'll be changing the response format to match the [DID Resolution Spec](https://w3c-ccg.github.io/did-resolution/)

**Comment by dmitrizagidulin** [comment]
(Mocked up from some of the response metadata in did-client cli)

**Pull request merged**
